CREATE Table IF NOT EXISTS MEMBER(
  MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
  NAME varchar(12) NOT NULL,
  EMAIL varchar(100) NOT NULL UNIQUE,
  password varchar(16) NOT NULL,
  CREATED_AT datetime NOT NULL,
  MODIFIED_AT datetime NOT NULL,
  PRIMARY KEY (MEMBER_ID)
);

CREATE Table IF NOT EXISTS QUESTION (
  QUESTION_ID bigint NOT NULL AUTO_INCREMENT,
  MEMBER_ID bigint NOT NULL,
  title varchar(50) NOT NULL,
  content varchar(100) NOT NULL,
  CREATED_AT datetime NOT NULL,
  MODIFIED_AT datetime NOT NULL,
  viewCount int NOT NULL,
  PRIMARY KEY (QUESTION_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE Table IF NOT EXISTS ANSWER (
  answer_id bigint NOT NULL AUTO_INCREMENT,
  question_id bigint NOT NULL,
  MEMBER_ID bigint NOT NULL,
  content varchar(100) NOT NULL,
  CREATED_AT datetime NOT NULL,
  MODIFIED_AT datetime NOT NULL,
  PRIMARY KEY (answer_id),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
);