CREATE Table IF NOT EXISTS MEMBER(
  MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
  NAME varchar(10) NOT NULL,
  EMAIL varchar(20) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  status varchar(255) NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MEMBER_ID)
);

CREATE Table IF NOT EXISTS QUESTION (
  QUESTION_ID bigint NOT NULL AUTO_INCREMENT,
  MEMBER_ID bigint NOT NULL,
  title varchar(255) NOT NULL,
  content varchar(10000) NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  viewCount int NOT NULL DEFAULT '0',
  PRIMARY KEY (QUESTION_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

CREATE Table IF NOT EXISTS ANSWER (
  answer_id bigint NOT NULL AUTO_INCREMENT,
  question_id bigint NOT NULL,
  MEMBER_ID bigint NOT NULL,
  content varchar(5000) NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (answer_id),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
  FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
);